name: Build

on:
  push:
    branches: [ "master" ]
    # tags:
    #   - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "The ${{ github.repository }} repository has been cloned."
    - run: echo "Setting up JDK" 
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - run: echo "The workflow is now ready to test your code."
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Get Action Path
      run: ${GITHUB_ACTION_PATH}
      shell: bash
    - name: Generate APK
      run: ./gradlew assembleRelease
    - name: Sign APK
      id: sign_aab
      uses: r0adkll/sign-android-release@v1
      with:
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Create Release APK
        path: ${{steps.sign_aab.outputs.signedReleaseFile}}
